### ISSUE TITLE
Attach moment to ajv instance?

### ISSUE THREAD

**Issue by epoberezkin** [cludden/ajv-moment#1]
It may be a nicer solution than passing via context - from version 4.6.0 all custom keywords (but "validate") receive the third parameter - schema compilation context that has reference to ajv instance `it.self`. In this way if the moment is attached to the instance, you can access it from custom keywords.

Or you could make moment a dependency of this package (there are pros and cons of course...)

**Comment by cludden** [comment]
@epoberezkin love the idea, but the issue I struggled with was the need to have moment available at validation time as opposed to compile time. As far as I can tell, there would be no way to access the ajv instance itself at validation time using the inline method, or am I missing something?

**Comment by epoberezkin** [comment]
Right, I was thinking about compilation time, where it's `it.self` :) But it's still available in inline keywords at validation time as `self` - I will add it to docs.

**Comment by cludden** [comment]
did not know about that, thanks for the sharing

**Comment by epoberezkin** [comment]
you're welcome. I think I may define some instance property where users can put their stuff to be certain it won't clash with any ajv stuff (like `res.locals` in express)... But in this particular case moment won't be there ever.
