### ISSUE TITLE
moment date value is not validating 

### ISSUE THREAD

**Issue by amehta11** [cludden/ajv-moment#4]
Hi,
   here is my code :
    
     `moment: {
                "format": ["YYYY-MM-DD HH:mm"],
                "validate": [
                    {
                        "test": "isSameOrAfter",
                        "value": moment().format("YYYY-MM-DD HH:mm")
                    }
                ]
        }`
   
 But the date is not validating by the plugin and always getting same error :
 `{
      "reason": "\"isSameOrAfter\" validation failed for value(s): null"
   }`
 
any suggestions.
thanks

**Comment by cludden** [comment]
Hey @amehta11 the schema must be valid JSON, not javascript. I believe you want
```json
{
    "format": ["YYYY-MM-DD HH:mm"],
    "validate": [
        {
            "test": "isSameOrAfter",
            "value": {
                "now": true
            }
        }
    ]
}
```

**Comment by amehta11** [comment]
hi @cludden thanks for reply. sorry didn't mention earlier that i did try with string as well. I used above code, now i have new error:

`Error while performing validation: Cannot read property '0' of undefined`

**Comment by cludden** [comment]
Any chance you can share a little more of your code (ie full schema) and where the error is being thrown (on validate, or compile)?

**Comment by cludden** [comment]
@amehta11 you're correct, this is a bug, will push a fix shortly
