### ISSUE TITLE
Validate returns invalid `dataPath`

### ISSUE THREAD

**Issue by bfeister** [cludden/ajv-moment#6]
Given the following code:
```
const VALID_SHIFT_ITEM = {
  required: ['totalCapacity', 'start', 'end'],
  properties: {
    totalCapacity: {
      type: 'integer',
      minimum: 1,
      maximum: OPPORTUNITY_SHIFT_MAX_CAPACITY,
    },
    remainingCapacity: {
      type: 'integer',
      minimum: 0,
      maximum: { $data: '1/totalCapacity' },
    },
    start: {
      required: ['localDateTime', 'timeZone'],
      properties: {
        localDateTime: {
          localDateTime: true,
          moment: {
            "validate": [
              {
                "test": "isAfter",
                "value": {
                  "$data": "2/end/localDateTime"
                }
              }
            ]
          }
        },
        timeZone: { type: 'string', minLength: 1 },
      },
    },
    end: {
      required: ['localDateTime', 'timeZone'],
      properties: {
        localDateTime: {
          localDateTime: true,
        },
        timeZone: { type: 'string', minLength: 1 },
      },
    },
  }
}
```
I get the following error returned from `validate()`

![image](https://user-images.githubusercontent.com/47546998/54647636-402d9600-4a71-11e9-9967-f595ca095c9e.png)

Note that the value is located at the schema root and says `localDateTime'` when it should actually be `localDateTime` (sans apostrophe) nested like this: `shifts/items/start/localDateTime`. 

A deeper look reveals that the error messages yielded by your plugin is as follows:

![image](https://user-images.githubusercontent.com/47546998/54647696-87b42200-4a71-11e9-854d-d02c03fd629b.png)

Note the double-encoded value wrapped in apostrophes. 

I believe the main AJV library is now storing this at `it.errorPath`

When defining my own `inline` validation, I find `it.errorPath` returns the value that I believe is needed here

![image](https://user-images.githubusercontent.com/47546998/54647827-10cb5900-4a72-11e9-8ca3-ac7917bf54bd.png)

however the code is so difficult to follow, I can't find where this is being declared in the pre-compilation code in order to produce the compiled result found in the `ajv-keywords` library:

https://github.com/epoberezkin/ajv-keywords/blob/master/keywords/dot/_formatLimit.jst

**Comment by cludden** [comment]
@bfeister my initial thoughts are that the schema looks wrong, the moment key should be nested in the type definition, where in your example, it appears as a sibling to the key its validating.. thoughts?

**Comment by cludden** [comment]
follow up, is `localDateTime` a key or validation schema member unrelated to this library?

**Comment by bfeister** [comment]
@cludden apologies for the confusion, but in my case `localDateTime` is _BOTH_ ... I should probably refactor that, but someone else wrote it so I'm just picking this up.

Hence the confusion, `localDateTime` is a key, and then nested under that key, it is valid as a valid schema member.

**Comment by bfeister** [comment]
As I'm sitting here trying to debug this, one thing that might clarify things would be how I take the value mentioned above `'shifts/' + i3 + '/start/localDateTime'` which is the correct value except that `i3` needs to be come the array index (`0` in this case). 

I presume there's some `it.util.something` function which returns the parsed value?
