### ISSUE TITLE
Broken in NPM

### ISSUE THREAD

**Issue by bfeister** [cludden/ajv-moment#9]
I think when you pushed the release tag after #8 you forgot to run `postrelease` or something like that? `yarn add` gives me an `ajv-moment` folder that lacks an `dist/index.js`

**Comment by cludden** [comment]
oops, try it now

**Comment by bfeister** [comment]
Ran `yarn cache clean ajv-moment && yarn install ajv-moment@2.0.2` but still getting no `dist/index.js`

**Comment by cludden** [comment]
v2.0.3
